[verification]
    # 新規ユーザーを認証する機能の設定
    # 有効にするか
    enable = true
    # 自己紹介チャンネルのID
    introduction_channel_id = "0000000000000000000"
    # 自動的に付与するロールのID
    role_id = "0000000000000000000"
    # 自己紹介に含めなければならないキーワード(正規表現対応)
    keyword = "[Ww]indows"