[general]
    # Botのトークン
    token = "YOUR_DISCORD_BOT_TOKEN"

[verification]
    # 新規ユーザーを認証する機能の設定
    # 有効にするか
    enable = true

    # 自己紹介チャンネルのID
    introduction_channel_id = "0000000000000000000"

    # 自動的に付与するロールのID
    role_id = "0000000000000000000"

    # 自己紹介に含めなければならないキーワード(正規表現対応)
    keyword = "[Ww]indows"

    # 合言葉が間違っていたユーザーに送信するDMメッセージ
    # `{name}`はユーザーの名前に置き換えられる
    dm_message_wrong = """
{name}さん、こんにちは。
合言葉が間違っています。再度入力してください。
編集では適用されないため注意が必要です。
"""

    # 合言葉が正しかったユーザーに送信するDMメッセージ
    # `{name}`はユーザーの名前に置き換えられる
    dm_message_correct = """
{name}さん、ようこそ。無事に認証されました。
"""